[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hpc_worker"
version = "0.1.0"
description = "HPC Worker for managing Ray clusters and datasets"
requires-python = ">=3.11"
dependencies = [
    "hypha-rpc",
    "ray[data,train,serve]",
    "pyyaml",
    "python-dotenv",
    "numpy"
]

[project.optional-dependencies]
dev = [
    "black",
    "ruff",
    "mypy",
    "pytest",
    "pytest-asyncio"
]

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"
